###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  
  - id: "{{package.name}}"
    name: Package extended scripts
    type: cli
    subtype: node
    version: "{{package.version}}"
    description: "{{package.description}}"
    homepage: "https://www.npmjs.com/package/@pigeon-posse/pkg-extended-scripts"
    repo: "https://github.com/pigeonposse/{{package.name}}"
    logo: "https://raw.githubusercontent.com/pigeonposse/{{package.name}}/main/docs/logo.png"
    banner: "https://raw.githubusercontent.com/pigeonposse/{{package.name}}/main/docs/banner.png"

###############################################################################
