###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  pes:
    name: "Package extended scripts"
    type:
      - cli
      - bin
      - library
    status: "active"
    version: "0.3.0"
    homepage: https://www.npmjs.com/package/@pigeon-posse/pkg-extended-scripts
    desc: "Separate scripts from package.json"
    logo: "https://raw.githubusercontent.com/pigeonposse/pkg-extended-scripts/main/docs/logo.png"
    banner: "https://raw.githubusercontent.com/pigeonposse/pkg-extended-scripts/main/docs/header.png"
    
###############################################################################
